# Generated by Django 4.1.6 on 2024-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='price_dialy',
        ),
        migrations.AddField(
            model_name='car',
            name='price_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='price_wek',
            field=models.IntegerField(default=0),
        ),
    ]
