# Generated by Django 4.1.6 on 2024-06-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_price_car_price_dialy_car_price_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='starter',
            field=models.IntegerField(default=0),
        ),
    ]
