# Generated by Django 4.1.6 on 2024-12-26 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('message', models.TextField(verbose_name='Message')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 23, 29, 18, 208193, tzinfo=datetime.timezone.utc)),
        ),
    ]
