# Generated by Django 4.1.6 on 2024-12-26 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_testimonial_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 23, 43, 15, 312721, tzinfo=datetime.timezone.utc)),
        ),
    ]
